### ISSUE TITLE
allow the same variable name to be used in different functions

### ISSUE THREAD

**Issue by ooovi** [DiffMu/DiffPrivacyInferenceHs#228] opened 2022-03-14 13:33 UTC
```
julia> typecheck_hs_from_string("
       module Foo
       function f()
          m = 1
       end
       function g()
          m = 2
       end
       end")
======================== Errors =====================

======================== End Errors =====================
Encountered error: An error regarding variable access types occured:
The variable 'm' ' is being mutated and read in two different scopes.
This is not allowed.

()
```
it's not really necessary, but has annoyed me on various occasions

**Comment by MxmUrw** [comment] 2022-03-15 14:21
Duplicate of #212

**Closed** 2022-03-15 14:21 UTC
Labels: enhancement
